version: '3.8'

services:
  mcp-server:
    build: .
    environment:
      - MCP_SERVER_NAME=my-mcp-server
      - MCP_SERVER_VERSION=1.0.0
      - DEBUG=false
    stdin_open: true
    tty: true
    volumes:
      - ./src:/app/src
      - ./config:/app/config